package before.find_the_differenc;

/**
 *
 * https://leetcode.com/problems/find-the-difference/
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 * 这题如果是有序的就好办了 直接遍历就行了
 * 无需的话但是只多了一个可以从0开始一次相加然后减去
 */
class Solution {
    public char findTheDifference(String s, String t) {
        char[] S = s.toCharArray();
        char[] T = t.toCharArray();
        int a = 0;
        for (int i = 0; i < S.length; i++) {
            a = a ^ S[i] ^ T[i];
        }
        a ^= T[T.length-1];
        return (char)a;
    }
}